-- MySQL Script generated by MySQL Workbench
-- Wed Nov 20 19:32:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema movie_theater_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movie_theater_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie_theater_schema` DEFAULT CHARACTER SET utf8 ;
USE `movie_theater_schema` ;

-- -----------------------------------------------------
-- Table `movie_theater_schema`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_theater_schema`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  `is_admin` TINYINT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_theater_schema`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_theater_schema`.`movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `poster_link` TEXT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_theater_schema`.`showtimes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_theater_schema`.`showtimes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `movie_id` INT NOT NULL,
  `showtime` DATETIME NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_showtimes_movies1_idx` (`movie_id` ASC) VISIBLE,
  CONSTRAINT `fk_showtimes_movies1`
    FOREIGN KEY (`movie_id`)
    REFERENCES `movie_theater_schema`.`movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_theater_schema`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_theater_schema`.`reservations` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reservations_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservations_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `movie_theater_schema`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie_theater_schema`.`seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie_theater_schema`.`seats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `seat_number` INT NOT NULL,
  `reservation_id` BIGINT NOT NULL,
  `showtime_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_seats_reservations1_idx` (`reservation_id` ASC) VISIBLE,
  INDEX `fk_seats_showtimes1_idx` (`showtime_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_seats_reservations1`
    FOREIGN KEY (`reservation_id`)
    REFERENCES `movie_theater_schema`.`reservations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seats_showtimes1`
    FOREIGN KEY (`showtime_id`)
    REFERENCES `movie_theater_schema`.`showtimes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
